### ISSUE TITLE
"allowlist"

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-permissions-policy#103]
See https://github.com/whatwg/xhr/pull/177#discussion_r157793031. Elsewhere we use "safelist" as alternative to "whitelist". Where does "allowlist" come from and does it make sense without space?

**Comment by clelland** [comment]
@jyasskin -- do you recall what led us to switch from 'whitelist/blacklist' to 'allowlist/blocklist'? I recall it being to match a decision that had been made for a different spec, but I don't remember the specifics.

**Comment by annevk** [comment]
We stopped using white/blacklist in Fetch/HTML/... due to their negative connotations, but used safelist/blocklist as replacements.

**Comment by jyasskin** [comment]
Yeah, we shouldn't associate "white" with good and "black" with bad.

**Comment by jyasskin** [comment]
I have an email from 2017-02-17 in which I suggest "allowlist" for Feature Policy without citing any precedent. I probably did a web search for alternatives and picked one that sounded good. Clearly I didn't check the HTML spec to see how it had replaced its terms. I have no objection to switching to "safelist".

I don't think I got this from WebAuthn. That spec used allowlist until https://github.com/w3c/webauthn/pull/489, but not quite for the same purpose.

**Comment by raymeskhoury** [comment]
It may also relate to the fact that the attribute name is "allow=...".

**Comment by annevk** [comment]
But it doesn't hold the structure backing allow it seems. It's just a set of origins (well, see #105). Perhaps it should just be called "origins" or some such.

**Comment by tomayac** [comment]
The character casing does look confusing in functions like `getAllowlistForFeature` ([§7.1.1 in the spec](
https://wicg.github.io/feature-policy/)) in the proposed JavaScript API. People new to this API (like me) might assume it is a typo.
