### ISSUE TITLE
What's the meaning of the 'Default allowlist' column?

### ISSUE THREAD

**Issue by jpmedley** [w3c/webappsec-permissions-policy#136]
Can you please clarify the meaning of the middle column [on this page](https://github.com/WICG/feature-policy/blob/gh-pages/features.md). Is this actually the default value? A list with one item only makes sense inside of computer code.

**Comment by clelland** [comment]
The [default allowlist](https://wicg.github.io/feature-policy/#default-allowlists) basically controls where the feature is allowed, in the absence of any other explicit policy.

`self` is a list  that contains just the origin of the current page
`*` is a list that contains *every* origin
`none` is an empty list

The spec link there goes into more detail about what exactly those mean.

(The names 'allowlist' and 'default allowlist' are certainly open to debate -- in the general form, an allowlist is a list of origins, maybe including items like `self`, or explicit origins like `https://www.example.com`, or some combination; this is the default value for that list)

**Comment by jpmedley** [comment]
I found the list of values. That's not the issue. What you're telling me is the column name actually means "default for allowlist". Most of us in the documentation business would just shorten that to "default".
