### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by Jxck** [w3c/webappsec-permissions-policy#142]
Like CSP, I wanna know where was blocked by feature policy.
but Spec says nothing about reporting-to/-uri.
is there any plan to do support reporting ?
or is there any reason not doing that ?

**Comment by clelland** [comment]
We are definitely planning to support reporting, through the [Reporting API](https://wicg.github.io/reporting/) (And the `Report-To` header). There are definitely reasons why it hasn't happened yet, specifically there are issues around reporting the behaviour of documents in cross-origin frames, but I'm hoping to have a proposal up here fairly soon to address that.

Thanks for opening this, btw -- we should use it for discussion of all of the issues around reporting.

**Comment by nico3333fr** [comment]
Yes, reporting could be useful to understand potential side-effects and deploy Feature Policy easily on websites.

**Comment by clelland** [comment]
Yes, @flano-yuki, that's true -- it looks like the header syntax was changed back in https://github.com/w3c/reporting/pull/67. I'll update that example, and ensure the changes make it into the spec eventually as well. Thanks!

**Comment by ebidel** [comment]
+1 for being able to specify an endpoint `group` using `report-to` directive. 

I think it's ok if browser-generated  interventions and deprecations are reported to the default group since you don't have control over those. But Feature Policy is a bit different since it's opt-in by the developer.

**Comment by clelland** [comment]
Closing this out as we've integrated reporting as of #529
