### ISSUE TITLE
Delineate relationship between Feature Policy and Origin Policy

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webappsec-permissions-policy#167]
Over in wicg.discourse.io, [ian_clelland writes in response](https://discourse.wicg.io/t/relationship-of-permissions-feature-policy-origin-policy/2772/3?u=equalsjeffh-pp) to [a query regarding the relationship between Feature Policy and Origin Policy](https://discourse.wicg.io/t/relationship-of-permissions-feature-policy-origin-policy/2772?u=equalsjeffh-pp):

> You would be able to use Origin Policy to set a Feature Policy header that would apply to every page on an origin. Currently, without Origin Policy, every page needs to be delivered with a header, and in a lot of use cases, that header should be exactly the same for every single page. Having to specify it for each page only increases bandwidth requirements and introduces the possibility of errors. Origin Policy should solve that, once it’s actually available.

AFAICT the [feature-policy](https://wicg.github.io/feature-policy/) spec does not as yet describe the above relationship.

**Comment by annevk** [comment]
Probably because Origin Policy is still unproven technology.

**Comment by mikewest** [comment]
What @annevk said. Chrome's prototyping an implementation right now, but the spec needs tons of work and is more of an idea of a thing we'd like to have than a thing we should be integrating with right now. Not sure how valuable it is to point to the doc in its current state.

**Comment by clelland** [comment]
OTOH, if the Origin Policy spec gets updated, it could definitely reference Feature Policy, either in HTTP header examples, or with dedicated syntax (similar to https://github.com/WICG/origin-policy/issues/19#issuecomment-321229817)

**Comment by mikewest** [comment]
Sure. @otherdaniel will get right on that. :)

**Comment by clelland** [comment]
Closing as Origin Policy is no longer being pursued.
