### ISSUE TITLE
HTTP headers not registered with IANA

### ISSUE THREAD

**Issue by clelland** [w3c/webappsec-permissions-policy#331]
`Feature-Policy` and `Feature-Policy-Report-Only` headers should be registered with the IANA, at least as Provisional Headers.

This will also come up with the document-policy headers, after a round of bikeshedding at least.

[Relevant RFC](https://tools.ietf.org/html/rfc3864)

**Comment by annevk** [comment]
Do we want to keep the "Feature Policy"-centric naming if we end up making this about permissions?

**Comment by SmashManiac** [comment]
@annevk I noticed that you created issues in https://github.com/protocol-registries/http-fields to register a bunch of HTTP headers, but not the ones from this thread. Is this normal? I would do it myself, but as a W3C outsider I'm not sure what URL to put.

**Comment by clelland** [comment]
Permissions-Policy header is registered; closing.
