### ISSUE TITLE
Remove '*' default allowlist

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-permissions-policy#381]
It doesn't seem like a desirable default value as it would allow third parties to prompt. See also https://github.com/privacycg/storage-access/issues/12.

**Comment by clelland** [comment]
Removing that would simplify the algorithms -- there would be exactly one default allowlist, `self`, and we could eliminate a few steps that assume it could be something different (that is, unless  https://github.com/privacycg/storage-access/issues/12 introduces another default)

The biggest use of '*' presently is `sync-xhr`; that currently needs to be allowed in all contexts by default; I don't think we can move to disabling it in all third-party embeds yet.

**Comment by annevk** [comment]
The alternative there would be making it a document policy only. Firefox doesn't ship `sync-xhr` for that reason.

**Comment by yoavweiss** [comment]
'*' is also used for low-entropy UA-CH, which should be sent by default (but which we want controlled).

**Comment by annevk** [comment]
@yoavweiss that sounds like a document policy then, not a permission policy.

**Comment by yoavweiss** [comment]
Can you expand on that?

**Comment by annevk** [comment]
https://github.com/w3c/webappsec-feature-policy/issues/298

**Comment by yoavweiss** [comment]
After looking into that, Client Hints should be a Permission Policy, not a Document Policy:
* The inheritance model desired for Client Hints fits Permission Policy's model
* Embedded content doesn't need to consent to having Client Hints delegated to it.

**Comment by annevk** [comment]
Well, but permissions aren't delegated by default to third parties.

**Comment by clelland** [comment]
That is one reason I was hesitant to make the rename -- yes, most permissions are not available to third parties without explicit delegation, but that's not the only possible model.

Client Hints generally fit the default 'self' shape. The low-entropy hints, though, are sent by default in all contexts. It should still be possible to disable them, if authors want to, and that shouldn't be overridable by embedded frames. At the same time, not receiving hints shouldn't require an opt-in like it would with Document Policy. Client hints, even the low-entropy hints, should behave like a permission which can be revoked, either by the user or the embedder.

**Comment by annevk** [comment]
It's hard for me to evaluate a Client Hints example as I don't know what the processing model for Client Hints is these days.

**Comment by yoavweiss** [comment]
https://wicg.github.io/client-hints-infrastructure/

**Comment by clelland** [comment]
Closing as not planned - there are a number of features shipped with '*' as their default, and it serves as a well-defined model for features which are generally available in all frames, but can be disabled at any point in the frame tree
