### ISSUE TITLE
Move Document Policy

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-permissions-policy#411]
As mentioned in passing in https://github.com/whatwg/xhr/pull/295 I think it would be better for it to be in its own repository. Also, as it's a new thing it should probably be incubated first?

**Comment by clelland** [comment]
We could do that... I thought that I remembered discussing that at TPAC2019, and that the sense at the time was that it wasn't necessary, but I don't see that represented in the official minutes at all.

The spec currently sits as an editor's draft in this repo, and is not represented in the WebAppSec charter. It should probably move, either into its own w3c/webappsec-document-policy repo, or to WICG, depending on whether there is consensus to adopt the work.

@mikewest, @dveditz -- as chairs, is this something that should be handled in a teleconference, or on the mailing list?

**Comment by clelland** [comment]
Discussion on the WebAppSec teleconference concluded that this can probably be incubated at WICG, and perhaps brought back to this group in the future.

**Comment by clelland** [comment]
It turns out this is not the first time this has been discussed; my memory clearly failed me. I [proposed this](https://discourse.wicg.io/t/proposal-document-policy/4483) on the WICG discourse back in May.

It appears that WICG may have a new process since then; I'll look into the current correct way to advance that.

**Comment by clelland** [comment]
Opened https://github.com/WICG/proposals/issues/15 to propose moving to WICG.

**Comment by clelland** [comment]
I've moved the spec and explainer to the new location at [WICG](https://github.com/WICG/document-policy), migrated all of the relevant issues, and updated links here to point to the new repo and/or spec as appropriate. If you see anything else stale, feel free to open an issue or PR to get it updated.
