### ISSUE TITLE
Proper delimiter clarification

### ISSUE THREAD

**Issue by patricktokeeffe** [w3c/webappsec-permissions-policy#418]
I ran into the same problem [this user](https://stackoverflow.com/q/66350784/2946116) had relating to the proper header definition of `Permissions-Policy` for *apache2*. After changing my list element separator from "`;`" to "`, `" I am no longer receiving errors. 

[This page](https://github.com/w3c/webappsec-permissions-policy/blob/main/permissions-policy-explainer.md#appendix-big-changes-since-this-was-called-feature-policy) describing new changes *does* specify users should use "`,`" instead of "`;`" as a list seperator. 

However, [this page](https://www.w3.org/TR/permissions-policy-1/#parse-policy-directive) still references the delimiter as "U+003B (;)". 

This issue is just to bring the discrepancy to your attention. If you feel this issue is filed in error, please feel free to close and, if you are able, provide a brief explanation. Thank you!

**Comment by annevk** [comment]
You want to look at https://w3c.github.io/webappsec-permissions-policy/. `TR/` drafts are routinely out-of-date. Having said that, in this case that part might be identical. I suspect it's not used for parsing the header, but rather the `allow` attribute, which still uses `;` as separator syntax.

**Comment by clelland** [comment]
That's correct (on both counts) -- the `allow` attribute does use a different syntax. The algorithm could probably have a note attached that mentions that it is only for the attribute.

**Comment by patricktokeeffe** [comment]
OK, thank you both for clarifying!
