### ISSUE TITLE
Make GitHub the preferred way to give feedback

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappsec-permissions-policy#427]
The SoTD suggest the mailing list is "preferred for discussion of this specification". We should fix this by setting the right thing via the "Issue Tracking" option in:
https://tabatkins.github.io/bikeshed/#metadata-issue-tracking

**Comment by clelland** [comment]
That section is auto-populated, as far as I can tell, based on the Repository being set (and inline issues in use). The `Boilerplate: feedback-header off` mechanism turns off the "Issue Tracking" section completely.

I can remove the mailing list with an empty "Mailing List" metadata, if that's appropriate.
