### ISSUE TITLE
Incorret grammar in Container policies green box

### ISSUE THREAD

**Issue by BrainCrumbz** [w3c/webappsec-permissions-policy#439]
There seems to be a typo or some missing word [here](https://github.com/w3c/webappsec-permissions-policy/blob/c099deb95328654f7ba7790ba62e37e6a655a08a/index.bs#L252), where it says:

> container policy can set by attributes on [...]

Maybe it should read:

> container policy can **_be_** set by attributes on [...]

or something similar?

HTH

**Comment by clelland** [comment]
Yep, thanks!
