### ISSUE TITLE
linkably define term "policy-controlled feature token"

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webappsec-permissions-policy#442]
currently the notion of a "[policy-controlled feature token](https://w3c.github.io/webappsec-permissions-policy/#:~:text=policy-controlled%20features%20are%20identified%20by%20tokens)" (related: "named Feature Policy", "features named", `feature-name`) is not formally defined and thus is awkward for other specs to refer to.

Thus I'm suggesting linkably defining the term "policy-controlled feature token".

See also: [Credential Management issue #184](https://github.com/w3c/webappsec-credential-management/issues/184) Add "policy controlled feature tokens" column to "Credential Types Registry"

**Comment by clelland** [comment]
I can add that as `[=policy-controlled feature/token=]`, defining 'token' specifically for policy-controlled features, and I think that we should be able to refer to it in exactly the same way.

**Comment by clelland** [comment]
https://github.com/w3c/webappsec-permissions-policy/commit/9d645680dd810053398e754207fb49e254e565de should fix this (and with an extra "#" it would have closed it, too)
