### ISSUE TITLE
add "otp-credentials" policy-controlled feature token to features.md

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/webappsec-permissions-policy#443]
The  [`otp`](https://wicg.github.io/web-otp/#OTPCredential)  [credential type](https://w3c.github.io/webappsec-credential-management/#credential-credential-type)'s specification defines the [`otp-credentials`](https://wicg.github.io/web-otp/#otp-credentials-feature) policy-controlled feature token, which is not yet represented in [features.md](https://github.com/w3c/webappsec-permissions-policy/blob/main/features.md), but probably ought to be.

/cc @samuelgoto @yi-gu @clelland

**Comment by summercms** [comment]
Thanks for info, I added it to a commit here: https://github.com/w3c/webappsec-permissions-policy/pull/473/commits/b8c61b6205456b0b55297b0198e264a8456c6b73
