### ISSUE TITLE
Mark "ambient-light-sensor" as behind a flag in features.md

### ISSUE THREAD

**Issue by o3-steven** [w3c/webappsec-permissions-policy#478]
Browser:
Chrome Version 103.0.5060.114

Error:
Error with Permissions-Policy header: Unrecognized feature: 'ambient-light-sensor'.

The above error is shown in the console while in the [features](https://github.com/w3c/webappsec-permissions-policy/blob/main/features.md) document shows it being available in Chrome 66. Reading into the issue on Chromium I suspect that ambient-light-sensor might be covered by the 'accelerometer' permission-policy and there is an item open to decouple them [Link](https://bugs.chromium.org/p/chromium/issues/detail?id=1340265&q=ambient%20light%20component%3ABlink%3ESensor&can=2)

Either way on the feature documentation could we get that cleared up?

**Comment by miketaylr** [comment]
"ambient-light-sensor" is supported in Chromium (see https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/permissions_policy/permissions_policy_features.json5;l=60-64?q=ambient-light-sensor%20file:json&start=31) - but will depend on the #enable-generic-sensor-extra-classes flag being enabled in chrome://flags/.

See https://chromestatus.com/feature/5298357018820608.

**Comment by o3-steven** [comment]
Hey @miketaylr I guess my initial confusion is due to the fact that other features hidden behind flags are clearly marked in the documentation while this one is not. Would it be possible to update the documentation?
