### ISSUE TITLE
Set up auto-publishing

### ISSUE THREAD

**Issue by clelland** [w3c/webappsec-permissions-policy#487]
In the spirit of living specs, we should set up auto-publishing to https://www.w3.org/TR/permissions-policy/

@sideshowbarker, who I think has access to do that.

(From #486)

**Comment by clelland** [comment]
@sideshowbarker ping on this -- is this something you can help with?

**Comment by sideshowbarker** [comment]
Wow, yeah — thanks for the ping, and very sorry for having neglected this until today

After the usual fumbling with various settings, just now got it working: https://www.w3.org/TR/permissions-policy/

**Comment by clelland** [comment]
That's okay, and thanks for the help!
