### ISSUE TITLE
"Process permissions policy attributes" unclear

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-permissions-policy#489]
This algorithm should only work for `iframe` elements, no? But step 1 seems awfully generic.

It also doesn't address the case when there is no `allow` attribute or element is not an `iframe` element.

**Comment by clelland** [comment]
Only `iframe` elements define `allow`, certainly.

The intention is for this mechanism to apply to any browsing context, so if the container is something else (`object` or `embed` or `frame`,) then we should either skip calling "Process permissions policy attributes", or else that algorithm should bail out early if *element* is not an `iframe` element. (That would keep the door open for extending it to allow additional browsing context containers in the future)
