### ISSUE TITLE
Clarify "Shipped in Chrome" for picture-in-picture in features.md

### ISSUE THREAD

**Issue by XSpielinbox** [w3c/webappsec-permissions-policy#502]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/picture-in-picture) the picture-in-picture directive has been supported in Chrome under the Feature-Policy name since version 71 and under the current (Permissions-Policy) name since version 88.
If this is correct, it would be nice to clarify this in this list here in features.md too.

At least in Brave 1.46.144 Chromium 108.0.5359.128 all [W3C Tests for picture-in-picture](http://w3c-test.org/picture-in-picture/) seem to work, except [css-selector](http://w3c-test.org/picture-in-picture/css-selector.html) and [shadow-dom](http://w3c-test.org/picture-in-picture/shadow-dom.html).

**Comment by clelland** [comment]
Thanks for noticing that! I was trying a new workflow, and ended up pushing all of my changes to my personal branch, not merging them in to this one 🤦 

It should be fixed now.
