### ISSUE TITLE
Does url match expression in origin with redirect count? takes a URL, not an origin

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-permissions-policy#519]
https://w3c.github.io/webappsec-permissions-policy/#allowlists doesn't appear to invoke it correctly. Origins aren't compatible with URLs.

**Comment by clelland** [comment]
This is probably going to have to end up using something like "let |url| be the result of calling the [[=url parser=]](https://url.spec.whatwg.org/#concept-url-parser) on the [[=serialization of an origin|serialization=]](https://html.spec.whatwg.org/multipage/browsers.html#ascii-serialisation-of-an-origin) of |origin|" to get an actual URL that can be used.

**Comment by annevk** [comment]
Yeah, though perhaps we could redo part of CSP whereby the first half of the algorithm or so becomes its own algorithm that we'd pass url's origin and Permissions Policy can invoke directly.

How does it actually work for paths today?

**Comment by clelland** [comment]
Do you mean paths in Permissions Policy declarations? I believe that in practice, paths have always been dropped from the string, and only the origin is used. (Chromium parses the URL, and then extracts the origin, throwing away the userinfo/path/query/fragment/whatever-else)

**Comment by annevk** [comment]
Hmm, it doesn't really make sense to me that you'd extract an origin from an expression. Perhaps you mean an origin-expression from a url-expression or some such? I can see ignoring/dropping the path though in the expression.

**Comment by clelland** [comment]
Sure -- before we had wildcard support, we would parse the string as a URL (assuming it wasn't `self`, `src` or `*`), and store only the origin of the parsed URL.

Now, I believe that we invoke the CSP parser on that string instead, which returns a [scheme/host/port/path struct](https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:services/network/public/mojom/content_security_policy.mojom;l=53), and we clear the path member before storing it in the allowlist.
