### ISSUE TITLE
"If the allowlist contains an origin representing self" is unclear

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-permissions-policy#520]
I think I kinda understand what this means, but this should be more explicit in some way.

**Comment by clelland** [comment]
I wasn't sure if the new text was clear enough -- from 4.7, allowlists can have "up to two additional [origins](https://url.spec.whatwg.org/#concept-url-origin) (one representing `self` and one representing `src`)."

Maybe it would be better to define two additional optional members on allowlist: one for an origin representing `self` and one for an origin representing `src`, and then refer to those by name.
