### ISSUE TITLE
methiyaowala

### ISSUE THREAD

**Issue by Usermsn** [w3c/webappsec-permissions-policy#535]
07881334  2
002065
031525
054161
F-3525824
PANYA YAOWALA
 ( AIA )
0107537002761
0872220535
3410200102061
*01401125350
341020009143     
3410200102096
41001470
165467
T-078813339
T078813342

**Comment by Usermsn** [comment]
> 07881334 2 002065 031525 054161 F-3525824 PANYA YAOWALA ( AIA ) 0107537002761 0872220535 3410200102061 *01401125350 341020009143 3410200102096 41001470 165467 T-078813339 T078813342

Mr.Methi Yaowala

**Comment by Userpanya** [comment]
THAILAND.Methi Yaowala
ข 5402072
ด.ช. วีระพันธ์เยาวลา
1-4102-00080-533
