### ISSUE TITLE
Permissions Policy report missing a document URL

### ISSUE THREAD

**Issue by shhnjk** [w3c/webappsec-permissions-policy#536]
The [current report structure](https://w3c.github.io/webappsec-permissions-policy/#algo-report-permissions-policy-violation) has  a [sourceFile](https://w3c.github.io/webappsec-permissions-policy/#permissionspolicyviolationreportbody-sourcefile). However, the script might be a third-party library, where the site owner does not know where this script is being executed.

The report should include a document URL, which indicates the URL of the document where the violation occured.

**Comment by shhnjk** [comment]
Never mind, this has been taken care in the reporting API.
https://www.w3.org/TR/reporting-1/#queue-report

**Comment by clelland** [comment]
Yes, sorry I didn't get to this right away; the outer report envelope has some of the universally-useful information that isn't report-type-specific.
