### ISSUE TITLE
[clipboard] document.execCommand('copy') and presumably paste bypass permissions policy

### ISSUE THREAD

**Issue by williewillus** [w3c/webappsec-permissions-policy#543]
Chromium bug https://issues.chromium.org/issues/327483127

Hi, I just noticed that the old `document.execCommand('copy')` call actually bypasses any permissions policy restrictions put on the clipboard, which seems like the wrong behaviour.
Can anyone confirm if this is intended?

I didn't test `execCommand('paste')`, but I suspect it also has the same issue.

**Comment by clelland** [comment]
Closing this here as it's not a permissions policy spec bug; the linked chromium issue is the right forum to figure out whether that's an implementation bug.
