### ISSUE TITLE
Update features.md (e.g., 'storage-access' is missing)

### ISSUE THREAD

**Issue by JannisBush** [w3c/webappsec-permissions-policy#551]
The `features.md` file does not seem up-to-date.
For example `storage-access` (https://privacycg.github.io/storage-access/#permissions-policy-integration) is missing.
There was #471 (#473), but that was closed without updating everything (and many changes happened since then).

On a more general note: 
The `features.md` file is manually updated at the moment and is thus probably often out-of-date. Would it be possible to have a more automatic process of creating such a file? For example getting the features from the Chromium source code, the features at chromestatus.com, or by parsing other spec documents that have a `Permissions Policy Integration` section?

**Comment by clelland** [comment]
Some time ago, I'd proposed making that a proper registry (https://github.com/w3c/webappsec-permissions-policy/pull/366) but that effort stalled. The current thinking (@marcoscaceres and @miketaylr to keep me honest here) is that we eventually plan to merge the concepts here with those in the Permissions API, and we can start by having a common unified registry of all features.

On the permissions end, I think that the external registry is being folded back into the main spec. Here, I want to get features.md up to date, and then merge its entire contents into the permissions spec, and deprecate it here.
